### ISSUE TITLE
Swift bridging header wrong/missing

### ISSUE THREAD

**Issue by SuperGeroy** [Hengyu/ChessEngine#1]
My Xcode 9.2 does not recognise the C classes you created.
Its error message is:
Use of undeclared type 'EngineManager' and 
Use of undeclared type 'EngineManagerDelegate'.
I guess it's about the bridging header between C and Swift.

**Comment by SuperGeroy** [comment]
I got it working.

**Comment by Yannick-91** [comment]
Hi SuperGeroy. Can you explain how your fixed ? I have the same issue right now
